apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: art-api
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.aftbay.com
      secretName: api-tls
  rules:
    - host: api.aftbay.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: art-api
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: art-web-admin
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - admin.aftbay.com
      secretName: admin-tls
  rules:
    - host: admin.aftbay.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: art-web-admin
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: art-docs
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - aftbay.com
        - www.aftbay.com
      secretName: docs-tls
  rules:
    - host: aftbay.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: art-docs
                port:
                  number: 80
    - host: www.aftbay.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: art-docs
                port:
                  number: 80
